const Role = {
    DELETE_ASSIGNMENT: 1,
    UPDATE_ASSIGNMENT: 2,
    CREATE_ASSIGNMENT: 4,
};

const RoleGroup = {
    ADMIN: Role.DELETE_ASSIGNMENT | Role.UPDATE_ASSIGNMENT | Role.CREATE_ASSIGNMENT,
    STUDENT: Role.UPDATE_ASSIGNMENT | Role.CREATE_ASSIGNMENT,
}

module.exports = Role;